language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
install: "pip3 install -r requirements.txt"
script:
    - python3 ./tests/basicparsing/nominal.py
    - python3 ./tests/backend/paraloop.py
